#!/bin/bash

# example repeat 10 echo hello
# To repeat the last command 10 times:
# repeat 10 !!
args=$@
cmd=${args#*$1}
declare -i num=$1
#echo $args
for i in $( seq 1 $num )
do
        $cmd
#done 2>&1
done 2>&1 | less -R
